# -*- coding: utf-8 -*-
"""class112.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJNOYGpDElA3uSvzk1DIIq_kXzJEnCP2
"""

import csv
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
import pandas as pd
import statistics
import  numpy as np
#from google.colab import files 
#data_to_load=files.upload()

#plotting the graph
df=pd.read_csv('Saving_data.csv')
fig=px.scatter(df,y='quant_saved',color='rem_any')
fig.show()

#bar graph for people who were given reminder vs who were not given reminder

with open('Saving_data.csv',newline="") as f:
  reader=csv.reader(f)
  savings_data=list(reader)
  savings_data.pop(0)
print(savings_data)

total_entries=len(savings_data)
total_people_given_reminder=0

for data in savings_data:
  if int(data[3])==1:
    total_people_given_reminder+=1

fig=go.Figure(go.Bar(x=['Reminded','Not reminded'],
              y=[total_people_given_reminder,
              (total_entries-total_people_given_reminder)]))
fig.show()

#Mean.median.mode of quant_saved

all_savings=[]
for data in savings_data:
  all_savings.append(float(data[0]))

mean_of_savings=statistics.mean(all_savings)
median_of_savings=statistics.median(all_savings)
mode_of_savings=statistics.mode(all_savings)

print("Mean of Savings=",mean_of_savings)
print("Median of Savings=",median_of_savings)
print("Mode of Savings=",mode_of_savings)

#mean.median,mode for people who got and did not get reminders
reminder_savings=[]
not_reminder_savings=[]

for data in savings_data:
  if int(data[3])==1:
    reminder_savings.append(float(data[0]))

  else:
    not_reminder_savings.append(float(data[0]))

mean_reminder=statistics.mean(reminder_savings)
median_reminder=statistics.median(reminder_savings)
mode_reminder=statistics.mode(reminder_savings)

mean_not_reminder=statistics.mean(not_reminder_savings)
median_not_reminder=statistics.median(not_reminder_savings)
mode_not_reminder=statistics.mode(not_reminder_savings)


print("Mean of reminder",mean_reminder)
print("Median of reminder",median_reminder)
print("Mode of reminder",mode_reminder)
print("\n\n")
print("Mean of not reminder",mean_not_reminder)
print("Median of not reminder",median_not_reminder)
print("Mode of reminder",mode_not_reminder)


print(f"Standard deviation of all the data->{statistics.stdev(all_savings)}")

print(f"Standard deviation of reminder data->{statistics.stdev(reminder_savings)}")
print(f"Standard deviation of not reminder data->{statistics.stdev(not_reminder_savings)}")

#correlation
age=[]
savings=[]
for data in savings_data:
  if float(data[5])!=0:
     age.append(float(data[5]))
     savings.append(float(data[0]))
   


correlation=np.corrcoef(age,savings)
print("Correlation ",correlation [0,1])

fig=ff.create_distplot([df['quant_saved'].tolist()],['Savings'],show_hist=False)
fig.show()